apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${HOST_PATH}"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
